version: '3.9'

services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    pid: "host"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/root/.config/glances/glances.conf"
    environment:
      - TZ=${TZ}
    command: ["python", "-m", "glances", "-C", "/root/.config/glances/glances.conf", "-w"]