version: '3.9'

services:
  glances:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    pid: "host"
    privileged: true
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./glances.conf:/glances/conf/glances.conf"
    environment:
      - TZ=${TZ}
      - "GLANCES_OPT=-w"